name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_AUTHORIZATION_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          key: ${{ secrets.HUMANX_KEY }}
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          script: |
            # JAR 파일 경로
            JAR_PATH="/home/ec2-user/fc-on/api/build/libs/fifa-0.0.1-SNAPSHOT.jar"
            # 포트
            PORT=8085
            # 프로필
            PROFILE="prod,security"

            # 폴더로 이동
            cd /home/ec2-user/fc-on/api

            # 소스 코드 업데이트
            echo "Pulling the latest changes from Git..."
            git pull

            # 빌드
            echo "Building the project..."
            ./gradlew build

            # 현재 실행 중인 프로세스 ID 확인
            PID=$(lsof -ti :$PORT)

            if [ -z "$PID" ]; then
              # 해당 포트를 사용하는 프로세스가 없으면 그냥 실행
              #nohup java -Dspring.profiles.active=$PROFILE -jar $JAR_PATH &
              nohup java -Dspring.profiles.active=$PROFILE -jar $JAR_PATH
              echo "Application started on port $PORT with profile $PROFILE."
            else
              # 해당 포트를 사용하는 프로세스가 있으면 종료 후 실행
              echo "Stopping application on port $PORT (PID: $PID)..."
              kill -9 $PID
              sleep 5
              echo "Starting application on port $PORT..."
              #nohup java -Dspring.profiles.active=$PROFILE -jar $JAR_PATH &
              nohup java -Dspring.profiles.active=$PROFILE -jar $JAR_PATH
              echo "Application restarted on port $PORT with profile $PROFILE."
            fi
      - name: Remove Github Actions IP From Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_AUTHORIZATION_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
